### ISSUE TITLE
meta::framework-gap: the job_workflow_sha pin in reusable workflows is a no-op — consumers silently run scripts/*.mjs from main, and sparse-checkout omits scripts/lib/

### ISSUE THREAD

**Issue by dsj1984** [dsj1984/mandrel-platform#414]
## Summary

The `ref:` that pins the shared-script checkout inside the reusable workflows —

```yaml
ref: ${{ fromJSON(toJSON(github)).job_workflow_sha }}
```

— **evaluates to an empty string at runtime**. `actions/checkout` omits empty
inputs and falls back to the repository's default branch, so consumers execute
`scripts/*.mjs` from **mandrel-platform `main`**, not from the SHA they pinned
their `uses:` to. The pin is decorative.

On its own that is a supply-chain and reproducibility defect. It became an
outage because it stacks with a second one: those same checkouts are
`sparse-checkout-cone-mode: false` with a hand-listed file set that does **not**
include `scripts/lib/`. So the first time a shared script on `main` imports a
helper from `scripts/lib/`, every consumer reds instantly, with no consumer-side
change and nothing to revert.

That happened today with #408.

## Evidence

Consumer: `Beestera/swarm-os`, which pins
`uptime-apply.yml@7203ff26c5594375f6aad09035ff521d735d6816` (v1.4.2).

Failing run: https://github.com/Beestera/swarm-os/actions/runs/33261495014

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module
  <workspace>/_mandrel-platform-uptime/scripts/lib/entry-guard.mjs
  imported from <workspace>/_mandrel-platform-uptime/scripts/apply-uptime-monitors.mjs
```

**The pin is ignored.** In that job's log, the checkout's `with:` dump contains
no `ref:` line at all, and the step resolves to the default branch:

```
git checkout --progress --force -B main refs/remotes/origin/main
git log -1 --format=%H  →  9e04147f264f365c40d6692eca72d4b1862be7dd
```

`9e04147f` is `main` (the merge commit of #408). The caller pinned `7203ff26`.
If the expression had evaluated, checkout would have landed on `7203ff26`.

**The two versions differ in exactly the way that matters.** Imports in
`scripts/apply-uptime-monitors.mjs`:

| ref | imports |
| --- | --- |
| `7203ff26` (pinned v1.4.2) | `node:fs`, `node:path` |
| `9e04147f` (`main`, #408) | `node:fs`, `node:path`, **`./lib/entry-guard.mjs`** |

**Timeline is exact.** #408 merged `2026-08-29T15:31:19Z`. The consumer's
previous `uptime-apply` run at `14:44Z` passed; the run at `15:54Z` — 23 minutes
after the merge, on an unrelated push — failed. No consumer commit touched
anything involved.

## Root cause

Two independent defects, either of which alone would have contained this:

1. **`fromJSON(toJSON(github)).job_workflow_sha` yields empty.** The
   actionlint escape hatch documented in the surrounding comment
   (`.github/workflows/uptime-apply.yml#L115-L119`) does not resolve the field.
   Worth confirming whether `github.job_workflow_sha` itself is populated for
   these calls before settling on a fix.
2. **`scripts/lib/` is absent from every sparse-checkout list**, while
   `sparse-checkout-cone-mode: false` makes the list exhaustive. A script's own
   module graph is not fetched with it.

## Blast radius — `deploy-cloudflare.yml` is next

The identical pattern (same comment, same expression, same omission) appears
three times on `main`:

| file | lines | sparse list |
| --- | --- | --- |
| `.github/workflows/uptime-apply.yml` | L119–L123 | `scripts/apply-uptime-monitors.mjs`, `.nvmrc` |
| `.github/workflows/deploy-cloudflare.yml` | L1176–L1179 | `scripts/deploy-worker-secrets.mjs` |
| `.github/workflows/deploy-cloudflare.yml` | L1277–L1280 | `scripts/deploy-boot-smoke.mjs` |

`deploy-boot-smoke.mjs` and `deploy-worker-secrets.mjs` have no `scripts/lib/`
import **yet**, so they are green today. The next helper refactor that touches
either — the same kind of change as #408 — reds consumers' **staging and
production deploys** by the identical mechanism.

## Suggested fix

Both halves, at all three sites:

1. Make the pin real — `ref: ${{ github.job_workflow_sha }}` with a scoped
   actionlint exclusion, rather than an escape hatch that fails open. Failing
   open is the dangerous direction here: an unresolvable pin should stop the
   job, not silently promote it to `main`.
2. Add `scripts/lib/` to every sparse-checkout list, so a script arrives with
   its module graph.

Worth considering as a regression guard: assert in CI that the checked-out
script SHA equals `job_workflow_sha`, which would have caught defect 1 at
introduction and would catch any future re-breakage regardless of cause.

## Consumer-side note

This is not fixable downstream. Both the `ref:` and the sparse list live inside
the reusable workflow, and re-pinning the caller to any other SHA changes
nothing — the pin is precisely what is being ignored. Consumers are blocked on
this repo.

**Comment by dsj1984** [comment]
**Superseded by #415** — *Make the reusable-workflow self-checkout pin real and fail-closed, and ship scripts/lib/ with the scripts that import it* (`type::story`, `agent::ready`).

Planned via `/plan --tickets 414`.

The analysis in this issue is preserved as the historical record; #415 carries the delivery contract.
